### ISSUE TITLE
voxel set abstraction module parameters

### ISSUE THREAD

**Issue by turboxin** [sshaoshuai/PV-RCNN#1]
Hi Dr. Shi@sshaoshuai, thanks your this great work！

I understand that it may still need some time before you could open source the pvrcnn code.  I‘m wondering could you please tell me the voxel set abstraction parameters first, since the paper only mentioned the radius at each level, what about the nsample and mlps? 

Looking forward to your reply. Thank you!

**Comment by sshaoshuai** [comment]
Here is the parameters of nsample and mlp:  
x_conv1: mlps[[16, 16],[16,16]], nsample [16, 16]
x_conv2: mlps[[32, 32],[32,32]], nsample [16, 32]
x_conv3: mlps[[64, 64],[64,64]], nsample [16, 32]
x_conv4: mlps[[64, 64],[64,64]], nsample [16, 32]
raw_points: mlps[[16, 16],[16,16]], nsample [16, 16]

For more parameters, please wait for the code release.

**Comment by turboxin** [comment]
Great! Thank you~
